class_name Items
const ICON_PATH = "res://Sprites/"

const ITEMS = {
	"Shadowsnipe": {
		"icon": ICON_PATH + "Shadow.png",
		"displayname": "Shadowsnipe",
		"details": "Cool, calm, and... a good lame. +50 Dollars",
		"trait1": "Lunar Squad",
		"trait2": "Gamer",
		"trait3": "1nsomn1akz",
		"score": 0,
		"multi": 0,
		"gold": 50,
		"time": 0,
		"cost": 5,
	},
	"APairOfPajamas": {
		"icon": ICON_PATH + "PJs.png",
		"displayname": "APairOfPajamas",
		"details": "Ready with the boombox and skakes! \n+15 Score",
		"trait1": "Lunar Squad",
		"trait2": "Green",
		"trait3": null,
		"score": 15,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"cost": 2,
	},
	"VI_Gura": {
		"icon": ICON_PATH + "VI_Gura.png",
		"displayname": "Gura (VI)",
		"details": "Gooba \n+30 Score, +1 Score Multiplier",
		"trait1": "VI",
		"trait2": "Shark",
		"trait3": "Affiliated",
		"score": 30,
		"multi": 1,
		"gold": 0,
		"time": 0,
		"cost": 4,
	},
	"VI_Alien": {
		"icon": ICON_PATH + "VI_Alien.png",
		"displayname": "Alien (VI)",
		"details":"\"Hey check it out.\"\n+15 Dollars",
		"trait1": "VI",
		"trait2": "Affiliated",
		"trait3": null,
		"score": 0,
		"multi": 0,
		"gold": 15,
		"time": 0,
		"cost": 3,
	},
	"VI": {
		"icon": ICON_PATH + "VI.png",
		"displayname": "VI",
		"details": "Quota for the night. +500 Cigarettes (Score)",
		"trait1": "VI",
		"trait2": "Gamer",
		"trait3": "Affiliated",
		"score": 500,
		"multi": 0,
		"gold": 00,
		"time": 0,
		"cost": 5,
	},
	"Sharky": {
		"icon": ICON_PATH + "Sharky.png",
		"displayname": "Sharky",
		"details": "If Helldivers 2 is so good, where's Helldivers 2 2 \n+25 Score, +2 Seconds",
		"trait1": "Shark",
		"trait2": "Affiliated",
		"trait3": null,
		"score": 25,
		"multi": 0,
		"gold": 0,
		"time": 2,
		"cost": 3,
	},
	"Serraphax": {
		"icon": ICON_PATH + "Serraphax.png",
		"displayname": "Serraphax",
		"details": "Stinky. \n+.3 Score Multiplier",
		"trait1": "Affiliated",
		"trait2":null,
		"trait3": null,
		"score": 0,
		"multi": .3,
		"gold": 0,
		"time": 0,
		"cost": 2,
	},
	"Nav": {
		"icon": ICON_PATH + "Nav.png",
		"displayname": "Navranth",
		"details": "Meowdy gamer.\n+10 Score, +.5 Score Multiplier",
		"trait1": "Cat",
		"trait2": null,
		"trait3": null,
		"score": 10,
		"multi": .5,
		"gold": 0,
		"time": 0,
		"cost": 3,
	},
	"CT": {
		"icon": ICON_PATH + "CT.png",
		"displayname": "Pray4Cthulhu",
		"details": "Somehow always laying down... \n+5 Seconds",
		"trait1": "Affiliated",
		"trait2": null,
		"trait3": null,
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 5,
		"cost": 2,
	},
	"Skye": {
		"icon": ICON_PATH + "Skye.png",
		"displayname": "Skye",
		"details": "Don't look at meeee! \n+10 Score, +3 Dollars",
		"trait1": "1nsomn1akz",
		"trait2": null,
		"trait3": null,
		"score": 10,
		"multi": 0,
		"gold": 3,
		"time": 0,
		"cost": 2,
	},
	"Kelly": {
		"icon": ICON_PATH + "Kelly.png",
		"displayname": "Kelly",
		"details": "Cat. \n+15 Score +2 Seconds",
		"trait1": "1nsomn1akz",
		"trait2": "Cat",
		"trait3": null,
		"score": 15,
		"multi": 0,
		"gold": 0,
		"time": 2,
		"cost": 3,
	},
	"Kawffi": {
		"icon": ICON_PATH + "Kawffi.png",
		"displayname": "Kawffi",
		"details": "Your favorite coffee based persona. \n +6 dollars",
		"trait1": "1nsomn1akz",
		"trait2": "Gamer",
		"trait3": null,
		"score": 0,
		"multi": 0,
		"gold": 6,
		"time": 0,
		"cost": 1,
	},
	"Mizuki": {
		"icon": ICON_PATH + "Mizuki.png",
		"displayname": "Mizuki",
		"details": "Tarkov Addict. Gaslighting Addict. +20 Score, +5 Dollars",
		"trait1": "1nsomn1akz",
		"trait2": "Gamer",
		"trait3": null,
		"score": 20,
		"multi": 0,
		"gold": 5,
		"time": 0,
		"cost": 4,
	},
	"Ewen": {
		"icon": ICON_PATH + "Ewen.png",
		"displayname": "Ewen",
		"details": "\"I'm so awesome!\" \n+5 Score",
		"trait1": "Green",
		"trait2": null,
		"trait3": null,
		"score": 5,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"cost": 1,
	},
	"Lemon": {
		"icon": ICON_PATH + "Lemon.png",
		"displayname": "Profit Lemon",
		"details": "NODDERS \n+2 Score, +3 Dollars",
		"trait1": "Lunar Squad",
		"trait2": null,
		"trait3": null,
		"score": 2,
		"multi": 0,
		"gold": 3,
		"time": 0,
		"cost": 1,
	},
	"Chachi": {
		"icon": ICON_PATH + "Chachi.png",
		"displayname": "Chachi",
		"details": "\"What chu' mean boy?\" \n+2 Score, +.01 Score Multiplier",
		"trait1": "Affiliated",
		"trait2": null,
		"trait3": null,
		"score": 2,
		"multi": .01,
		"gold": 0,
		"time": 0,
		"cost": 1,
	},
	"Arba": {
		"icon": ICON_PATH + "Arba.png",
		"displayname": "Arbalust",
		"details": "\"I'm just teasing!\" \n+7 Score, +7 Dollars, +1 Seconds",
		"trait1": "Lunar Squad",
		"trait2": "Cat",
		"trait3": null,
		"score": 7,
		"multi": 0,
		"gold": 7,
		"time": 1,
		"cost": 3,
	},
	"Rinny": {
		"icon": ICON_PATH + "Rinny.png",
		"displayname": "Rinny",
		"details": "Looking for their husband.\n+10 Dollars",
		"trait1": "Green",
		"trait2": "Gamer",
		"trait3": null,
		"score": 0,
		"multi": 0,
		"gold": 10,
		"time": 0,
		"cost": 2,
	},
	"Kiv": {
		"icon": ICON_PATH + "Kiv.png",
		"displayname": "Kivarwe",
		"details": "Redhead fox. Pool shark. +5 Score, +3 Dollars, +.01 Score Multiplier",
		"trait1": "Lunar Squad",
		"trait2": "Shark",
		"trait3": null,
		"score": 5,
		"multi": .01,
		"gold": 3,
		"time": 0,
		"cost": 2,
	},
	"MrMe": {
		"icon": ICON_PATH + "MrMe.png",
		"displayname": "Mr.Me",
		"details": "Mr. Me or... Big Chungus..? \n+20 Dollars, +10 Score",
		"trait1": "Lunar Squad",
		"trait2": null,
		"trait3": null,
		"score": 10,
		"multi": 0,
		"gold": 20,
		"time": 0,
		"cost": 4,
	},
	"Jusu": {
		"icon": ICON_PATH + "Jusu.png",
		"displayname": "Jusu",
		"details": "Snoozsu, momsu, or Jusu. +30 Score, +30 Dollars, +10 Seconds",
		"trait1": "1nsomn1akz",
		"trait2": null,
		"trait3": null,
		"score": 30,
		"multi": 0,
		"gold": 30,
		"time": 10,
		"cost": 5,
	},
	"Falnen": {
		"icon": ICON_PATH + "Falnen.png",
		"displayname": "Falnen",
		"details": "Missing in action. Not rogue.\n+3 Seconds, +15 Score",
		"trait1": "1nsomn1akz",
		"trait2": null,
		"trait3": null,
		"score": 15,
		"multi": 0,
		"gold": 0,
		"time": 3,
		"cost": 4,
	},
	"Havie": {
		"icon": ICON_PATH + "Havie.png",
		"displayname": "Havie",
		"details": "\"I'll be back in a bit\" (Won't come back) +1 Dollar +1 seconds",
		"trait1": "1nsomn1akz",
		"trait2": null,
		"trait3": null,
		"score": 0,
		"multi": 0,
		"gold": 1,
		"time": 1,
		"cost": 1,
	},
	"Kosen": {
		"icon": ICON_PATH + "Kosen.png",
		"displayname": "Kosen",
		"details": "Local purple oni. \n+2 Dollars, + 2 Score",
		"trait1": "1nsomn1akz",
		"trait2": null,
		"trait3": null,
		"score": 2,
		"multi": 0,
		"gold": 2,
		"time": 0,
		"cost": 1,
	},
	"Renko": {
		"icon": ICON_PATH + "Renko.png",
		"displayname": "Renko",
		"details": "Not schizophrenic. There are definitely cats here. \n+2 Seconds, +7 Score",
		"trait1": "Affiliated",
		"trait2": "Gamer",
		"trait3": null,
		"score": 7,
		"multi": 0,
		"gold": 0,
		"time": 2,
		"cost": 2,
	},
	"Nia": {
		"icon": ICON_PATH + "Nia.png",
		"displayname": "Nia",
		"details": "Live Nia Reaction??? \n +2 Dollars, +4 Score, +1 Seconds",
		"trait1": "1nsomn1akz",
		"trait2": "Green",
		"trait3": "Cat",
		"score": 4,
		"multi": 0,
		"gold": 2,
		"time": 1,
		"cost": 2,
	},
	"Maki": {
		"icon": ICON_PATH + "Maki.png",
		"displayname": "Maki",
		"details": "Rawrrawr~ \n+1 Time, +3 Score",
		"trait1": "1nsomn1akz",
		"trait2": null,
		"trait3": null,
		"score": 3,
		"multi": 0,
		"gold": 0,
		"time": 3,
		"cost": 1,
	}
}

const TRAITS = {
	"Lunar Squad": {
		"icon": ICON_PATH + "LunSquad.png",
		"traitName" : "Lunar Squad",
		"desc" : "Increases Score by 10,000",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"Shark": {
		"icon": ICON_PATH + "shark.png",
		"traitName" : "Shark",
		"desc" : "Increases Econ by 1",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"VI": {
		"icon": ICON_PATH + "Insom.png",
		"traitName" : "VI",
		"desc" : "Increases Score by 5x, Reduces Time by Half",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"Gamer": {
		"icon": ICON_PATH + "Insom.png",
		"traitName" : "Gamer",
		"desc" : "Increases Score by 2x",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"1nsomn1akz": {
		"icon": ICON_PATH + "Insom.png",
		"traitName" : "1nsomn1akz",
		"desc" : "Increases time by 2x",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"Cat": {
		"icon": ICON_PATH + "cat.png",
		"traitName" : "Cat",
		"desc" : "Increases time by 2x",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"Affiliated": {
		"icon": ICON_PATH + "moist.png",
		"traitName" : "Affiliated",
		"desc" : "Increases time by 2x",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"Green": {
		"icon": ICON_PATH + "green.png",
		"traitName" : "",
		"desc" : "",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	},
	"null": {
		"icon": ICON_PATH + "Insom.png",
		"traitName" : "",
		"desc" : "",
		"score": 0,
		"multi": 0,
		"gold": 0,
		"time": 0,
		"timeMulti" : 0,
		"count" : 0,
	}
}
